name: Update README with latest Activity

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: TechPhil/github-activity-readme@dev
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
